GMAIL_USERNAME: 'gilbertlcsndle@gmail.com'
GMAIL_PASSWORD: 'HuyK550023320055'
ADMIN_EMAIL: admin@example.com
ADMIN_PASSWORD: password
PAYPAL_USERNAME: gilbert.lacasandile_api1.gmail.com
PAYPAL_PASSWORD: TCDJ8A6DBA4DMRC9
PAYPAL_SIGNATURE: Ar.tS8OliPfCHiX3nqA61aSskAcoA3PKfOAjUS.s57U2CQ5Sze02msfY
PAYPAL_PERSONAL_EMAIL: gilbert.lacasandile-personal@gmail.com
PAYPAL_PERSONAL_PASSWORD: BnwE0100297792001
